hero component and styles
alexascript/alexascript-webpage pull request #8
Opened 2024-03-04 20:19 UTC by alexascript

Creates the Hero component including the Title, text, button and image. Adds styles to the component and general page.

2024-03-04 20:26 UTC, locke189 requested changes

2024-03-04 20:26 UTC, locke189 commented on react/alexascript/src/components/hero/hero.js
> +export function Hero({ title }) {
Please create props for the title, text, imageUrl and buttonCopy.

2024-03-05 19:56 UTC, alexascript commented on react/alexascript/src/components/hero/hero.js
> +export function Hero({ title }) {
The props are created: Title, text, imageUrl and buttonCopy.

2024-03-05 21:25 UTC, locke189 approved these changes

2024-03-05 21:26 UTC, merged